src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_jours;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="formation")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNombreJours(): ?int
    {
        return $this->nombre_jours;
    }

    public function setNombreJours(int $nombre_jours): self
    {
        $this->nombre_jours = $nombre_jours;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addFormation($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeFormation($this);
        }

        return $this;
    }
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('nombre_jours')
            ->add('date_debut')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @IsGranted("ROLE_STAGIAIRE")
 * @Route("/formation")
 */
class FormationController extends AbstractController
{
    /**
     * @Route("/", name="formation_index", methods={"GET"})
     */
    public function index(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/index.html.twig', [
            'formations' => $formationRepository->findAll(),
        ]);
    }

    /**
     * * @IsGranted("ROLE_FORMATEUR")
     * @Route("/new", name="formation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $formation = new Formation();
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formation);
            $entityManager->flush();

            return $this->redirectToRoute('formation_index');
        }

        return $this->render('formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formation_show", methods={"GET"})
     */
    public function show(Formation $formation): Response
    {
        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="formation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Formation $formation): Response
    {
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('formation_index');
        }

        return $this->render('formation/edit.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Formation $formation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($formation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formation_index');
    }
}

templates/formation/_delete_form.html.twig
<form method="post" action="{{ path('formation_delete', {'id': formation.id}) }}" onsubmit="return confirm('Êtes vous certain.e de vouloir effacer cette formation ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
<button type="submit" class="btn btn-danger">{{ button_label|default('Effacer') }}</button>

</form>

templates/formation/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button type="submit" class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/formation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formation{% endblock %}

{% block body %}
    <h1>Editer Formation</h1>

    {{ include('formation/_form.html.twig', {'button_label': 'Éditer'}) }} {{ include('formation/_delete_form.html.twig') }}
{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation index
{% endblock %}

{% block body %}
	<h1>Formation index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Nom</th>
				<th>Nombre_jours</th>
				<th>Date_debut</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for formation in formations %}
				<tr>
					<td>{{ formation.id }}</td>
					<td>{{ formation.nom }}</td>
					<td>{{ formation.nombreJours }}</td>
					<td>{{ formation.dateDebut ? formation.dateDebut|date('d-m-Y') : '' }}</td>
					<td>
						<a href="{{ path('formation_show', {'id': formation.id}) }}">voir</a>
						{% if is_granted('ROLE_FORMATEUR') %}
							<a href="{{ path('formation_edit', {'id': formation.id}) }}">éditer</a>
						{% endif %}


					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5">Pas de Formation</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% if is_granted('ROLE_FORMATEUR') %}
		<a href="{{ path('formation_new') }}">Ajouter une formation</a>
	{% endif %}

{% endblock %}

templates/formation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formation{% endblock %}

{% block body %}
    <h1>Créer une nouvelle formation</h1>

    {{ include('formation/_form.html.twig') }}



<a href="{{ path('home') }}">
	<button class="btn btn-primary">{{ button_label|default('Retour') }}</button>
</a>
<a href="{{ path('formation_index') }}">
	<button class="btn btn-info">{{ button_label|default('Toutes les formations') }}</button>
</a>


{% endblock %}

templates/formation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation
{% endblock %}

{% block body %}
	<h1>Formation</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ formation.id }}</td>
			</tr>
			<tr>
				<th>Nom</th>
				<td>{{ formation.nom }}</td>
			</tr>
			<tr>
				<th>Nombre_jours</th>
				<td>{{ formation.nombreJours }}</td>
			</tr>
			<tr>
				<th>Date_debut</th>
				<td>{{ formation.dateDebut ? formation.dateDebut|date('Y-m-d') : '' }}</td>
			</tr>
		</tbody>
	</table>

	{% if is_granted('ROLE_FORMATEUR') %}
		{{ include('formation/_delete_form.html.twig') }}
		<a href="{{ path('formation_index') }}">
			<button class="btn btn-info">{{ button_label|default('Toutes les formations') }}</button>
		</a>

	{% endif %}

	<a href="{{ path('home') }}">
		<button class="btn btn-primary">{{ button_label|default('Retour') }}</button>
        
	</a>


{% endblock %}